resources:
- https://github.com/radhacms/argocd.git//telemetry/prometheus?ref=main

configMapGenerator:
- envs:
  - config/env.properties
  name: env-configmap

components:
- https://github.com/radhacms/argocd.git//telemetry/common?ref=main
- ../components/us-west-2

patchesStrategicMerge:
- uswest2-netpol-patch.yaml

